apiVersion: v1
kind: Secret
metadata:
  name: session
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
type: Opaque
stringData: 
  session: '{{ ( include "secret.session" . ) | indent 2 -}}'